[project]
name = "miur"
version = "0.1.3"
requires-python = ">=3.12"
description = "Modern Interface for Uniform Reconnaissance"
readme = "README.rst"
authors = [{ name="Dmytro Kolomoiets", email="amerlyq+code@gmail.com" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: POSIX :: Linux",
]

[project.urls]
Homepage = "https://github.com/miur/miur"
Issues = "https://github.com/miur/miur/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
