#!/usr/bin/env bash
set -o errexit -o errtrace -o functrace -o noclobber -o noglob -o nounset -o pipefail

## NEED:(for ubuntu-22.04):
# sudo add-apt-repository ppa:deadsnakes/ppa
# sudo apt-get -yq satisfy python3.14{,-dev,-venv}
# sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.10 10
# sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.14 14
# sudo update-alternatives --set python /usr/bin/python3.14
# curl -LOJ https://bootstrap.pypa.io/get-pip.py
# python get-pip.py
# python -m pip --version
# python -m pip install --upgrade pip  # setuptools packaging wheel pip-tools
# python -m pip install --upgrade ipython jupyter_console black isort pylint mypy python-lsp-server python-lsp-black pylsp-mypy pyls-isort

this=$(realpath -e "${BASH_SOURCE[0]:-$0}")

d_pj=${this%/*/*}
ln -svfT "$d_pj/run" /b/miur
ver=$(python -c 'import sys; print(f"{(ver:=sys.version_info)[0]}.{ver[1]}")')
ln -svfT "$d_pj/src" ~/.local/lib/"python$ver"/site-packages/miur
ln -svfT miur /b/mi

exit

startdir=${this%/*}
source "$startdir/../archlinux/PKGBUILD.dev"

if [[ ${1-} == "--direct" ]]; then
  # pkgdir=/tmp/miur
  pkgdir=""
  package
else
  ver=$(sed -r '/^__version__\s*=\s*"([^"]+)"/s//\1/' "$startdir/../../src/_pkg.py")

  # FAIL: "sudo checkinstall" on error or <C-c> nukes whole /lib on ubuntu>=20.04 due to its DFL="--fstrans=no",
  #   including /lib/ld-linux-x86-64.so.2 which makes whole system disfunctional (not even /bin/ls works)
  checkinstall -y --install=no --fstrans=yes --pkgname="$pkgname" --pkgversion="$ver" \
    --provides="${pkgname%-dev}" --pkggroup=development --maintainer="${USER}@${HOST}" \
      --nodoc "$this" "--direct"  # --requires="zlib1g"
fi
